export const LANGUAGE_OPTIONS = [
  { locale: "en", label: "English" },
  { locale: "de", label: "Deutsch" },
  { locale: "es", label: "Español" },
  { locale: "fr", label: "Français" },
  { locale: "it", label: "Italiano" },
  { locale: "ru", label: "Русский" },
  { locale: "zh", label: "中文" },
  { locale: "tw", label: "繁體中文" },
  { locale: "jp", label: "日本語" },
  { locale: "ko", label: "한국어" },
  { locale: "br", label: "Português (BR)" },
  { locale: "mx", label: "Español (MX)" },
  { locale: "pl", label: "Polski" },
  { locale: "tr", label: "Türkçe" },
  { locale: "vi", label: "Tiếng Việt" },
  { locale: "hi", label: "हिन्दी" },
  { locale: "ms", label: "Bahasa Melayu" },
] as const;

export const UI_STRINGS: Record<string, Record<string, string>> = {
  en: {
    pageTitle: "AoE2 Civilization Quiz",
    setupTitle: "Create Quiz",
    setupDescription: "Choose the question types you want, then start a new run with your current preferences.",
    languageHeading: "Language",
    questionLanguageLabel: "Question language",
    questionTypesHeading: "Question Types",
    questionTypeBonuses: "Civilization Bonuses",
    questionTypeUnits: "Unique Units",
    questionTypeTechs: "Unique Technologies",
    questionTypeTeam: "Team Bonus",
    questionCountHeading: "Question Count",
    startQuizButton: "Start Quiz",
    settingsTitle: "Settings",
    lightMode: "Light mode",
    closeButton: "Close",
    resultsTitle: "Quiz Overview",
    resultsTotal: "Total",
    resultsCorrect: "Correct",
    resultsWrong: "Wrong",
    resultsAccuracy: "Accuracy",
    rerunWrongOnly: "Rerun Wrong Only",
    createNewQuiz: "Create New Quiz",
    noWrongAnswers: "No Wrong Answers",
    fallbackCivBonus: "Civ Bonus",
    fallbackUniqueUnit: "Unique Unit",
    fallbackUniqueTech: "Unique Tech",
    fallbackTeamBonus: "Team Bonus",
    errorLoadingQuiz: "Error loading quiz data. Please refresh the page.",
  },
  de: {
    pageTitle: "AoE2-Zivilisationsquiz",
    setupTitle: "Quiz erstellen",
    setupDescription: "Wähle die gewünschten Fragetypen aus und starte eine neue Runde mit deinen aktuellen Einstellungen.",
    languageHeading: "Sprache",
    questionLanguageLabel: "Fragesprache",
    questionTypesHeading: "Fragetypen",
    questionTypeBonuses: "Zivilisationsboni",
    questionTypeUnits: "Einzigartige Einheiten",
    questionTypeTechs: "Einzigartige Technologien",
    questionTypeTeam: "Teambonus",
    questionCountHeading: "Fragenanzahl",
    startQuizButton: "Quiz starten",
    settingsTitle: "Einstellungen",
    lightMode: "Hellmodus",
    closeButton: "Schließen",
    resultsTitle: "Quiz-Übersicht",
    resultsTotal: "Gesamt",
    resultsCorrect: "Richtig",
    resultsWrong: "Falsch",
    resultsAccuracy: "Trefferquote",
    rerunWrongOnly: "Nur falsche Fragen erneut",
    createNewQuiz: "Neues Quiz erstellen",
    noWrongAnswers: "Keine falschen Antworten",
    fallbackCivBonus: "Zivilisationsbonus",
    fallbackUniqueUnit: "Einzigartige Einheit",
    fallbackUniqueTech: "Einzigartige Technologie",
    fallbackTeamBonus: "Teambonus",
    errorLoadingQuiz: "Fehler beim Laden der Quizdaten. Bitte lade die Seite neu.",
  },
  es: {
    pageTitle: "Quiz de civilizaciones AoE2",
    setupTitle: "Crear quiz",
    setupDescription: "Elige los tipos de pregunta que quieras y comienza una nueva partida con tus preferencias actuales.",
    languageHeading: "Idioma",
    questionLanguageLabel: "Idioma de las preguntas",
    questionTypesHeading: "Tipos de pregunta",
    questionTypeBonuses: "Bonificaciones de civilización",
    questionTypeUnits: "Unidades únicas",
    questionTypeTechs: "Tecnologías únicas",
    questionTypeTeam: "Bonificación de equipo",
    questionCountHeading: "Cantidad de preguntas",
    startQuizButton: "Empezar quiz",
    settingsTitle: "Configuración",
    lightMode: "Modo claro",
    closeButton: "Cerrar",
    resultsTitle: "Resumen del quiz",
    resultsTotal: "Total",
    resultsCorrect: "Correctas",
    resultsWrong: "Incorrectas",
    resultsAccuracy: "Precisión",
    rerunWrongOnly: "Repetir solo falladas",
    createNewQuiz: "Crear nuevo quiz",
    noWrongAnswers: "Sin respuestas incorrectas",
    fallbackCivBonus: "Bonificación de civilización",
    fallbackUniqueUnit: "Unidad única",
    fallbackUniqueTech: "Tecnología única",
    fallbackTeamBonus: "Bonificación de equipo",
    errorLoadingQuiz: "Error al cargar los datos del quiz. Actualiza la página.",
  },
  fr: {
    pageTitle: "Quiz des civilisations AoE2",
    setupTitle: "Créer un quiz",
    setupDescription: "Choisissez les types de questions souhaités, puis lancez une nouvelle partie avec vos préférences actuelles.",
    languageHeading: "Langue",
    questionLanguageLabel: "Langue des questions",
    questionTypesHeading: "Types de questions",
    questionTypeBonuses: "Bonus de civilisation",
    questionTypeUnits: "Unités uniques",
    questionTypeTechs: "Technologies uniques",
    questionTypeTeam: "Bonus d'équipe",
    questionCountHeading: "Nombre de questions",
    startQuizButton: "Démarrer le quiz",
    settingsTitle: "Paramètres",
    lightMode: "Mode clair",
    closeButton: "Fermer",
    resultsTitle: "Aperçu du quiz",
    resultsTotal: "Total",
    resultsCorrect: "Correctes",
    resultsWrong: "Fausses",
    resultsAccuracy: "Précision",
    rerunWrongOnly: "Rejouer seulement les erreurs",
    createNewQuiz: "Créer un nouveau quiz",
    noWrongAnswers: "Aucune mauvaise réponse",
    fallbackCivBonus: "Bonus de civilisation",
    fallbackUniqueUnit: "Unité unique",
    fallbackUniqueTech: "Technologie unique",
    fallbackTeamBonus: "Bonus d'équipe",
    errorLoadingQuiz: "Erreur lors du chargement des données du quiz. Veuillez actualiser la page.",
  },
  it: {
    pageTitle: "Quiz delle civiltà AoE2",
    setupTitle: "Crea quiz",
    setupDescription: "Scegli i tipi di domanda che desideri e avvia una nuova partita con le tue preferenze attuali.",
    languageHeading: "Lingua",
    questionLanguageLabel: "Lingua delle domande",
    questionTypesHeading: "Tipi di domanda",
    questionTypeBonuses: "Bonus civiltà",
    questionTypeUnits: "Unità uniche",
    questionTypeTechs: "Tecnologie uniche",
    questionTypeTeam: "Bonus di squadra",
    questionCountHeading: "Numero di domande",
    startQuizButton: "Avvia quiz",
    settingsTitle: "Impostazioni",
    lightMode: "Modalità chiara",
    closeButton: "Chiudi",
    resultsTitle: "Panoramica quiz",
    resultsTotal: "Totale",
    resultsCorrect: "Corrette",
    resultsWrong: "Sbagliate",
    resultsAccuracy: "Precisione",
    rerunWrongOnly: "Ripeti solo quelle sbagliate",
    createNewQuiz: "Crea un nuovo quiz",
    noWrongAnswers: "Nessuna risposta sbagliata",
    fallbackCivBonus: "Bonus civiltà",
    fallbackUniqueUnit: "Unità unica",
    fallbackUniqueTech: "Tecnologia unica",
    fallbackTeamBonus: "Bonus di squadra",
    errorLoadingQuiz: "Errore nel caricamento dei dati del quiz. Aggiorna la pagina.",
  },
  ru: {
    pageTitle: "Викторина по цивилизациям AoE2",
    setupTitle: "Создать викторину",
    setupDescription: "Выберите нужные типы вопросов и начните новый раунд с текущими настройками.",
    languageHeading: "Язык",
    questionLanguageLabel: "Язык вопросов",
    questionTypesHeading: "Типы вопросов",
    questionTypeBonuses: "Бонусы цивилизаций",
    questionTypeUnits: "Уникальные юниты",
    questionTypeTechs: "Уникальные технологии",
    questionTypeTeam: "Командный бонус",
    questionCountHeading: "Количество вопросов",
    startQuizButton: "Начать викторину",
    settingsTitle: "Настройки",
    lightMode: "Светлая тема",
    closeButton: "Закрыть",
    resultsTitle: "Итоги викторины",
    resultsTotal: "Всего",
    resultsCorrect: "Верно",
    resultsWrong: "Неверно",
    resultsAccuracy: "Точность",
    rerunWrongOnly: "Повторить только неверные",
    createNewQuiz: "Создать новую викторину",
    noWrongAnswers: "Нет неверных ответов",
    fallbackCivBonus: "Бонус цивилизации",
    fallbackUniqueUnit: "Уникальный юнит",
    fallbackUniqueTech: "Уникальная технология",
    fallbackTeamBonus: "Командный бонус",
    errorLoadingQuiz: "Ошибка загрузки данных викторины. Обновите страницу.",
  },
  zh: {
    pageTitle: "AoE2 文明测验",
    setupTitle: "创建测验",
    setupDescription: "选择你想要的题目类型，然后使用当前偏好开始新一局。",
    languageHeading: "语言",
    questionLanguageLabel: "题目语言",
    questionTypesHeading: "题目类型",
    questionTypeBonuses: "文明加成",
    questionTypeUnits: "特色单位",
    questionTypeTechs: "特色科技",
    questionTypeTeam: "团队加成",
    questionCountHeading: "题目数量",
    startQuizButton: "开始测验",
    settingsTitle: "设置",
    lightMode: "浅色模式",
    closeButton: "关闭",
    resultsTitle: "测验概览",
    resultsTotal: "总计",
    resultsCorrect: "正确",
    resultsWrong: "错误",
    resultsAccuracy: "准确率",
    rerunWrongOnly: "仅重做错误题",
    createNewQuiz: "创建新测验",
    noWrongAnswers: "没有错误答案",
    fallbackCivBonus: "文明加成",
    fallbackUniqueUnit: "特色单位",
    fallbackUniqueTech: "特色科技",
    fallbackTeamBonus: "团队加成",
    errorLoadingQuiz: "加载测验数据时出错。请刷新页面。",
  },
  tw: {
    pageTitle: "AoE2 文明測驗",
    setupTitle: "建立測驗",
    setupDescription: "選擇你想要的題目類型，然後使用目前偏好開始新一輪。",
    languageHeading: "語言",
    questionLanguageLabel: "題目語言",
    questionTypesHeading: "題目類型",
    questionTypeBonuses: "文明加成",
    questionTypeUnits: "特殊單位",
    questionTypeTechs: "特殊科技",
    questionTypeTeam: "團隊加成",
    questionCountHeading: "題目數量",
    startQuizButton: "開始測驗",
    settingsTitle: "設定",
    lightMode: "淺色模式",
    closeButton: "關閉",
    resultsTitle: "測驗總覽",
    resultsTotal: "總計",
    resultsCorrect: "正確",
    resultsWrong: "錯誤",
    resultsAccuracy: "準確率",
    rerunWrongOnly: "只重做錯題",
    createNewQuiz: "建立新測驗",
    noWrongAnswers: "沒有錯誤答案",
    fallbackCivBonus: "文明加成",
    fallbackUniqueUnit: "特殊單位",
    fallbackUniqueTech: "特殊科技",
    fallbackTeamBonus: "團隊加成",
    errorLoadingQuiz: "載入測驗資料時發生錯誤。請重新整理頁面。",
  },
  jp: {
    pageTitle: "AoE2 文明クイズ",
    setupTitle: "クイズを作成",
    setupDescription: "出題タイプを選んで、現在の設定で新しいクイズを開始しましょう。",
    languageHeading: "言語",
    questionLanguageLabel: "問題の言語",
    questionTypesHeading: "出題タイプ",
    questionTypeBonuses: "文明ボーナス",
    questionTypeUnits: "固有ユニット",
    questionTypeTechs: "固有テクノロジー",
    questionTypeTeam: "チームボーナス",
    questionCountHeading: "問題数",
    startQuizButton: "クイズ開始",
    settingsTitle: "設定",
    lightMode: "ライトモード",
    closeButton: "閉じる",
    resultsTitle: "クイズ概要",
    resultsTotal: "合計",
    resultsCorrect: "正解",
    resultsWrong: "不正解",
    resultsAccuracy: "正答率",
    rerunWrongOnly: "間違いのみ再挑戦",
    createNewQuiz: "新しいクイズを作成",
    noWrongAnswers: "不正解はありません",
    fallbackCivBonus: "文明ボーナス",
    fallbackUniqueUnit: "固有ユニット",
    fallbackUniqueTech: "固有テクノロジー",
    fallbackTeamBonus: "チームボーナス",
    errorLoadingQuiz: "クイズデータの読み込みでエラーが発生しました。ページを再読み込みしてください。",
  },
  ko: {
    pageTitle: "AoE2 문명 퀴즈",
    setupTitle: "퀴즈 만들기",
    setupDescription: "원하는 문제 유형을 선택하고 현재 설정으로 새 퀴즈를 시작하세요.",
    languageHeading: "언어",
    questionLanguageLabel: "문제 언어",
    questionTypesHeading: "문제 유형",
    questionTypeBonuses: "문명 보너스",
    questionTypeUnits: "고유 유닛",
    questionTypeTechs: "고유 기술",
    questionTypeTeam: "팀 보너스",
    questionCountHeading: "문제 수",
    startQuizButton: "퀴즈 시작",
    settingsTitle: "설정",
    lightMode: "라이트 모드",
    closeButton: "닫기",
    resultsTitle: "퀴즈 개요",
    resultsTotal: "전체",
    resultsCorrect: "정답",
    resultsWrong: "오답",
    resultsAccuracy: "정확도",
    rerunWrongOnly: "오답만 다시 풀기",
    createNewQuiz: "새 퀴즈 만들기",
    noWrongAnswers: "틀린 답이 없습니다",
    fallbackCivBonus: "문명 보너스",
    fallbackUniqueUnit: "고유 유닛",
    fallbackUniqueTech: "고유 기술",
    fallbackTeamBonus: "팀 보너스",
    errorLoadingQuiz: "퀴즈 데이터를 불러오는 중 오류가 발생했습니다. 페이지를 새로고침하세요.",
  },
  br: {
    pageTitle: "Quiz de Civilizações de AoE2",
    setupTitle: "Criar quiz",
    setupDescription: "Escolha os tipos de pergunta desejados e inicie uma nova rodada com suas preferências atuais.",
    languageHeading: "Idioma",
    questionLanguageLabel: "Idioma das perguntas",
    questionTypesHeading: "Tipos de pergunta",
    questionTypeBonuses: "Bônus de civilização",
    questionTypeUnits: "Unidades únicas",
    questionTypeTechs: "Tecnologias únicas",
    questionTypeTeam: "Bônus de equipe",
    questionCountHeading: "Quantidade de perguntas",
    startQuizButton: "Iniciar quiz",
    settingsTitle: "Configurações",
    lightMode: "Modo claro",
    closeButton: "Fechar",
    resultsTitle: "Visão geral do quiz",
    resultsTotal: "Total",
    resultsCorrect: "Corretas",
    resultsWrong: "Incorretas",
    resultsAccuracy: "Precisão",
    rerunWrongOnly: "Repetir apenas as erradas",
    createNewQuiz: "Criar novo quiz",
    noWrongAnswers: "Nenhuma resposta errada",
    fallbackCivBonus: "Bônus de civilização",
    fallbackUniqueUnit: "Unidade única",
    fallbackUniqueTech: "Tecnologia única",
    fallbackTeamBonus: "Bônus de equipe",
    errorLoadingQuiz: "Erro ao carregar os dados do quiz. Atualize a página.",
  },
  mx: {
    pageTitle: "Quiz de civilizaciones AoE2",
    setupTitle: "Crear quiz",
    setupDescription: "Elige los tipos de pregunta que quieras y comienza una nueva ronda con tus preferencias actuales.",
    languageHeading: "Idioma",
    questionLanguageLabel: "Idioma de las preguntas",
    questionTypesHeading: "Tipos de pregunta",
    questionTypeBonuses: "Bonificaciones de civilización",
    questionTypeUnits: "Unidades únicas",
    questionTypeTechs: "Tecnologías únicas",
    questionTypeTeam: "Bonificación de equipo",
    questionCountHeading: "Cantidad de preguntas",
    startQuizButton: "Iniciar quiz",
    settingsTitle: "Configuración",
    lightMode: "Modo claro",
    closeButton: "Cerrar",
    resultsTitle: "Resumen del quiz",
    resultsTotal: "Total",
    resultsCorrect: "Correctas",
    resultsWrong: "Incorrectas",
    resultsAccuracy: "Precisión",
    rerunWrongOnly: "Repetir solo incorrectas",
    createNewQuiz: "Crear nuevo quiz",
    noWrongAnswers: "Sin respuestas incorrectas",
    fallbackCivBonus: "Bonificación de civilización",
    fallbackUniqueUnit: "Unidad única",
    fallbackUniqueTech: "Tecnología única",
    fallbackTeamBonus: "Bonificación de equipo",
    errorLoadingQuiz: "Error al cargar los datos del quiz. Actualiza la página.",
  },
  pl: {
    pageTitle: "Quiz cywilizacji AoE2",
    setupTitle: "Utwórz quiz",
    setupDescription: "Wybierz typy pytań, które chcesz, a następnie rozpocznij nową rundę z bieżącymi ustawieniami.",
    languageHeading: "Język",
    questionLanguageLabel: "Język pytań",
    questionTypesHeading: "Typy pytań",
    questionTypeBonuses: "Premie cywilizacji",
    questionTypeUnits: "Unikalne jednostki",
    questionTypeTechs: "Unikalne technologie",
    questionTypeTeam: "Premia drużynowa",
    questionCountHeading: "Liczba pytań",
    startQuizButton: "Rozpocznij quiz",
    settingsTitle: "Ustawienia",
    lightMode: "Jasny motyw",
    closeButton: "Zamknij",
    resultsTitle: "Podsumowanie quizu",
    resultsTotal: "Razem",
    resultsCorrect: "Poprawne",
    resultsWrong: "Błędne",
    resultsAccuracy: "Dokładność",
    rerunWrongOnly: "Powtórz tylko błędne",
    createNewQuiz: "Utwórz nowy quiz",
    noWrongAnswers: "Brak błędnych odpowiedzi",
    fallbackCivBonus: "Premia cywilizacji",
    fallbackUniqueUnit: "Unikalna jednostka",
    fallbackUniqueTech: "Unikalna technologia",
    fallbackTeamBonus: "Premia drużynowa",
    errorLoadingQuiz: "Błąd podczas wczytywania danych quizu. Odśwież stronę.",
  },
  tr: {
    pageTitle: "AoE2 Medeniyet Bilgi Yarışması",
    setupTitle: "Bilgi yarışması oluştur",
    setupDescription: "İstediğiniz soru türlerini seçin ve mevcut tercihlerinizle yeni bir tur başlatın.",
    languageHeading: "Dil",
    questionLanguageLabel: "Soru dili",
    questionTypesHeading: "Soru türleri",
    questionTypeBonuses: "Medeniyet bonusları",
    questionTypeUnits: "Özel birimler",
    questionTypeTechs: "Özel teknolojiler",
    questionTypeTeam: "Takım bonusu",
    questionCountHeading: "Soru sayısı",
    startQuizButton: "Yarışmayı başlat",
    settingsTitle: "Ayarlar",
    lightMode: "Aydınlık mod",
    closeButton: "Kapat",
    resultsTitle: "Yarışma özeti",
    resultsTotal: "Toplam",
    resultsCorrect: "Doğru",
    resultsWrong: "Yanlış",
    resultsAccuracy: "Başarı oranı",
    rerunWrongOnly: "Sadece yanlışları tekrar çöz",
    createNewQuiz: "Yeni yarışma oluştur",
    noWrongAnswers: "Yanlış cevap yok",
    fallbackCivBonus: "Medeniyet bonusu",
    fallbackUniqueUnit: "Özel birim",
    fallbackUniqueTech: "Özel teknoloji",
    fallbackTeamBonus: "Takım bonusu",
    errorLoadingQuiz: "Yarışma verileri yüklenirken hata oluştu. Lütfen sayfayı yenileyin.",
  },
  vi: {
    pageTitle: "Đố vui nền văn minh AoE2",
    setupTitle: "Tạo câu đố",
    setupDescription: "Chọn kiểu câu hỏi bạn muốn, rồi bắt đầu một lượt mới với các thiết lập hiện tại.",
    languageHeading: "Ngôn ngữ",
    questionLanguageLabel: "Ngôn ngữ câu hỏi",
    questionTypesHeading: "Kiểu câu hỏi",
    questionTypeBonuses: "Thưởng nền văn minh",
    questionTypeUnits: "Đơn vị đặc biệt",
    questionTypeTechs: "Công nghệ đặc biệt",
    questionTypeTeam: "Thưởng đồng đội",
    questionCountHeading: "Số câu hỏi",
    startQuizButton: "Bắt đầu",
    settingsTitle: "Cài đặt",
    lightMode: "Chế độ sáng",
    closeButton: "Đóng",
    resultsTitle: "Tổng kết câu đố",
    resultsTotal: "Tổng",
    resultsCorrect: "Đúng",
    resultsWrong: "Sai",
    resultsAccuracy: "Độ chính xác",
    rerunWrongOnly: "Làm lại chỉ câu sai",
    createNewQuiz: "Tạo câu đố mới",
    noWrongAnswers: "Không có câu sai",
    fallbackCivBonus: "Thưởng nền văn minh",
    fallbackUniqueUnit: "Đơn vị đặc biệt",
    fallbackUniqueTech: "Công nghệ đặc biệt",
    fallbackTeamBonus: "Thưởng đồng đội",
    errorLoadingQuiz: "Lỗi khi tải dữ liệu câu đố. Vui lòng làm mới trang.",
  },
  hi: {
    pageTitle: "AoE2 सभ्यता प्रश्नोत्तरी",
    setupTitle: "प्रश्नोत्तरी बनाएं",
    setupDescription: "जिन प्रश्न प्रकारों को आप चाहते हैं, उन्हें चुनें और अपनी वर्तमान प्राथमिकताओं के साथ एक नया राउंड शुरू करें।",
    languageHeading: "भाषा",
    questionLanguageLabel: "प्रश्न भाषा",
    questionTypesHeading: "प्रश्न प्रकार",
    questionTypeBonuses: "सभ्यता बोनस",
    questionTypeUnits: "विशिष्ट इकाइयाँ",
    questionTypeTechs: "विशिष्ट तकनीकें",
    questionTypeTeam: "टीम बोनस",
    questionCountHeading: "प्रश्नों की संख्या",
    startQuizButton: "प्रश्नोत्तरी शुरू करें",
    settingsTitle: "सेटिंग्स",
    lightMode: "लाइट मोड",
    closeButton: "बंद करें",
    resultsTitle: "प्रश्नोत्तरी सारांश",
    resultsTotal: "कुल",
    resultsCorrect: "सही",
    resultsWrong: "गलत",
    resultsAccuracy: "सटीकता",
    rerunWrongOnly: "केवल गलत दोबारा करें",
    createNewQuiz: "नई प्रश्नोत्तरी बनाएं",
    noWrongAnswers: "कोई गलत उत्तर नहीं",
    fallbackCivBonus: "सभ्यता बोनस",
    fallbackUniqueUnit: "विशिष्ट इकाई",
    fallbackUniqueTech: "विशिष्ट तकनीक",
    fallbackTeamBonus: "टीम बोनस",
    errorLoadingQuiz: "प्रश्नोत्तरी डेटा लोड करने में त्रुटि। कृपया पेज रीफ़्रेश करें।",
  },
  ms: {
    pageTitle: "Kuiz Tamadun AoE2",
    setupTitle: "Cipta kuiz",
    setupDescription: "Pilih jenis soalan yang anda mahu, kemudian mulakan pusingan baharu dengan pilihan semasa anda.",
    languageHeading: "Bahasa",
    questionLanguageLabel: "Bahasa soalan",
    questionTypesHeading: "Jenis soalan",
    questionTypeBonuses: "Bonus tamadun",
    questionTypeUnits: "Unit unik",
    questionTypeTechs: "Teknologi unik",
    questionTypeTeam: "Bonus pasukan",
    questionCountHeading: "Bilangan soalan",
    startQuizButton: "Mula kuiz",
    settingsTitle: "Tetapan",
    lightMode: "Mod cerah",
    closeButton: "Tutup",
    resultsTitle: "Ringkasan kuiz",
    resultsTotal: "Jumlah",
    resultsCorrect: "Betul",
    resultsWrong: "Salah",
    resultsAccuracy: "Ketepatan",
    rerunWrongOnly: "Ulang hanya yang salah",
    createNewQuiz: "Cipta kuiz baharu",
    noWrongAnswers: "Tiada jawapan salah",
    fallbackCivBonus: "Bonus tamadun",
    fallbackUniqueUnit: "Unit unik",
    fallbackUniqueTech: "Teknologi unik",
    fallbackTeamBonus: "Bonus pasukan",
    errorLoadingQuiz: "Ralat memuatkan data kuiz. Sila muat semula halaman.",
  },
};
